### PR TITLE
feat: add support for a connection string

### PR DESCRIPTION
**Pull request by sromic**
Adding support for a connection string option.

Related to the issue: #115

### CODE REVIEW

**Comment by sromic** [comment]
Hi @jeremydaly 
please review this PR and if you think this makes sense to be added to this awesome lib :)

**Review by naorpeled — APPROVED** [review]
LGTM,
let's add a test to validate this though

**Comment by sromic** [comment]
> LGTM, let's add a test to validate this though

@naorpeled tests are added :) 
Also did a little refactoring on `config` method as well as ts type def.

**Comment by naorpeled** [comment]
> > LGTM, let's add a test to validate this though
> 
> @naorpeled tests are added :) 
> Also did a little refactoring on `config` method as well as ts type def.

Awesome, will talk to Jeremy and aim to merge this sometime throughout the weekend

**Comment by sromic** [comment]
@naorpeled any news on this?

**Comment by naorpeled** [comment]
> @naorpeled any news on this?

Hey,
sorry for the delay, was super swamped with stuff to do and forgot about this.

Will message Jeremy now 🙏

**Comment by naorpeled** [comment]
Hey @sromic,
updating that I've sent a message to Jeremy 2 days ago.
Will let you know when I have any updates 🙏

**Comment by sromic** [comment]
> Hey @sromic, updating that I've sent a message to Jeremy 2 days ago. Will let you know when I have any updates 🙏

@naorpeled Much appreciated!

**Pull request merged**
