### PR TITLE
Update typescript definition

### PR DESCRIPTION
**Pull request by deptno**
apply #5

### CODE REVIEW

**Comment by shrugs** [comment]
I'm not super familiar with the ts type definition language, but is it possible to "declare" the `ServerlessMysql` type in that file?

The ideal situation is that I can do `import createConnection, {ServerlessMysql} from 'serverless-mysql` in a typescript file and use that type across my code.

**Comment by jeremydaly** [comment]
Reviewing.

**Comment by deptno** [comment]
Local test is OK.

usage

```typescript
import serverlessMysql, {ServerlessMysql} from 'serverless-mysql'

const mysql: ServerlessMysql = serverlessMysql({
  backoff: 'string',
  base: 1,
  cap: 1,
  config: {
    host: 'same as mysql config'
  },
  connUtilization: 1,
  manageConns: true,
  maxConnsFreq: 1,
  maxRetries: 1,
  onClose() {},
  onConnect() {},
  onConnectError() {},
  onError() {},
  onKill() {},
  onKillError() {},
  onRetry() {},
  usedConnsFreq: 1,
  zombieMaxTimeout: 1,
  zombieMinTimeout: 1,
})
```

**Comment by shrugs** [comment]
Works well on my end!

**Comment by h3llrais3r** [comment]
Can a release be done with these changes? Otherwise I'll have to use my own typings until this is released.

EDIT: can you also fix the implicit any warnings?
https://github.com/jeremydaly/serverless-mysql/blob/master/index.d.ts#L82
https://github.com/jeremydaly/serverless-mysql/blob/master/index.d.ts#L93

should be: `(...args: any[])` to prevent the error when compiling with `noImplicitAny` compiler flag:
```
node_modules/serverless-mysql/index.d.ts(82,12): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
node_modules/serverless-mysql/index.d.ts(93,9): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
```

**Pull request merged**
